name: Update and Restart Server

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send HTTP request to Pterodactyl
        run: |
          curl -X POST https://panel.cheapserver.fun/server/73156fba \
          -H 'Authorization: Bearer ${{ secrets.PTERODACTYL_API_KEY }}' \
          -H 'Content-Type: application/json' \
          -d '{"signal": "restart"}'
